### ISSUE TITLE
warning file of check_input is long and not well formated

### ISSUE THREAD

**Issue by karchern** [zellerlab/stag#13]
Hi Alessio,

I ran stag check_input in order to check the data for several thousand sequences and their taxonomy. Some sequences are identical but have different taxonomy, which stag thankfully noticed. Unfortunately, the output file is not very informative, since it doesn't specify what the problem is. It simply prints many lines that start with "Warning" followed by a list of gene names. I could only see what the problem is by manually checking the taxonomy file for those genes.

It also seems like many of those lines are duplicated (I assume stag check_input prints one such warning line per incoherent sequence. If some gene sequences are identical many times, many warning lines will be duplicated).

Cheers,
Nic

**Comment by AlessioMilanese** [comment]
Hi @karchern ,

I added the possibility to save the warning messages to a file in 01032b7151b33d1823ad43aa37b06364292df67a . You can just use the option `-w` to specify a file where to save the warning messages.

At the moment it is saving only the warning messages for the case when genes have same sequence, but different taxonomy.

> It also seems like many of those lines are duplicated (I assume stag check_input prints one such warning line per incoherent sequence. If some gene sequences are identical many times, many warning lines will be duplicated).

I think this should be taken care of, but maybe good to double check.
