### ISSUE TITLE
10 singel-copy marker genes

### ISSUE THREAD

**Issue by INFINITY1993** [zellerlab/stag#38]
Hi,
Thanks for developing this tool.
For genome classification, how were the 10 marker genes selected?
Thanks!

**Comment by AlessioMilanese** [comment]
Thank you for your message and for your interest in the tool. The 10 marker genes used for genome classification were selected from the mOTUs profiler, which is a widely-used tool for microbial community profiling. The marker genes chosen are universal protein coding genes that have good phylogenetic properties, meaning that they can be used to accurately track the evolutionary relationships between different microorganisms.

You can find more information about the selection of the marker genes and the mOTUs profiler in the following papers:

- "mOTUs: accurate and comprehensive profiling of microbial communities from shotgun metagenomic data" (Nature Methods, 2014) - https://www.nature.com/articles/nmeth.2693
- "Improved mapping and profiling of microbial communities using the mOTUs2 framework" (Nature Communications, 2019) - https://www.nature.com/articles/s41467-019-08844-4
- "mOTUs3: an accurate and efficient method for profiling and taxonomic classification of microbial communities" (Microbiome, 2022) - https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-022-01410-z

I hope this information helps. Let me know if you have any other questions.

**Comment by INFINITY1993** [comment]
Thank you so much! This information is very helpful to me!
